### ISSUE TITLE
percy-selenium-java 1.1.0 doesn't work together with @percy/cli@1.16.0

### ISSUE THREAD

**Issue by it-ony** [percy/percy-selenium-java#176]
## The problem

calling `.snapshot("name")` throws

```
java.lang.ClassCastException: class com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to class java.lang.String (com.google.common.collect.Maps$TransformedEntriesMap is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

```

with @percy/cli = 1.16.0

## Environment

- `@percy/cli` version: 1.16.0
- Version of Percy SDK you’re using: 1.1.0

## Code to reproduce issue

```
npm install -g @percy/cli@1.16.0
PERCY_TOKEN=<YOUR_TOKEN> percy exec:start
```

see that [simple test](https://github.com/it-ony/percy-bug/blob/master/src/test/java/PercyIT.java)

## Details

works with `@percy/cli` on version `1.14.0`

basically, there error is that the new version returns a map with the keys, `html`, `warnings` and `resources` instead (my assumption) the html only.

**Comment by itsjwala** [comment]
* @it-ony thanks for the prompt, we're aware of this issue and have pushed a patch https://github.com/percy/percy-selenium-java/issues/172, we'll release `v1.2.0` today to resolve this. 
* current workaround is using `@percy/cli@v1.14.0`

**Comment by it-ony** [comment]
I can confirm it's fixed with v.1.2.0
